In [2]:
import pandas as pd
import seaborn as sns
%matplotlib inline
%config InlineBackend.figure_format='retina'

From: https://opendata.moac.go.th/?p=list-data&sp=list-data-info&id=0000000061

In [7]:
area = pd.read_csv("https://opendata.moac.go.th/subControl/downloadFile/downloadFile.php?id=0000000500")
area.tail(20)

,ปี,จังหวัด,พื้นที่ชุมชนและสิ่งปลูกสร้าง,พื้นที่นา,พืชไร่,ไม้ยืนต้น,ไม้ผล,พืชสวน,ไร่หมุนเวียน,ทุ่งหญ้าเลี้ยงสัตว์และโรงเรือนเลี้ยงสัตว์,พืชน้ำ,สถานที่เพาะเลี้ยงสัตว์น้ำ,เกษตรผสมผสาน/ไร่นาสวนผสม,ป่าสมบูรณ์,ป่ารอสภาพฟื้นฟู,พื้นที่น้ำ,พื้นที่ลุ่ม,พื้นที่เบ็ดเตล็ดอื่น ๆ,รวมพื้นที่,link
94,2561,กาญจนบุรี,337391,439649,2237380.0,556912,162183,103784.0,NaN,18714,NaN,4433.0,NaN,7123863.0,375321.0,557043,8507,251788,12176968,http://www1.ldd.go.th/web_OLP/Lu_61/Lu61_C/map...
95,2561,ประจวบคีรีขันธ์,230535,72826,514395.0,647094,518572,4227.0,NaN,6267,228.0,77097.0,NaN,1612462.0,36396.0,59783,53908,145972,3979762,http://www1.ldd.go.th/web_OLP/Lu_61/Lu61_C/map...
96,2561,เพชรบุรี,193918,415563,270631.0,135894,230445,20236.0,NaN,6491,95.0,63134.0,39.0,2162628.0,68736.0,92591,15071,215239,3890711,http://www1.ldd.go.th/web_OLP/Lu_61/Lu61_C/map...
97,2561,กำแพงเพชร,276114,1357854,1992010.0,171238,119843,6072.0,2299.0,5471,NaN,3656.0,1272.0,1270557.0,20610.0,97819,18381,36485,5379681,http://www1.ldd.go.th/web_OLP/Lu_61/Lu61_N/map...
98,2561,เชียงราย,423948,1446452,982599.0,639323,430727,13273.0,213613.0,12255,13.0,28124.0,2235.0,2746175.0,89199.0,108536,46846,115663,7298981,http://www1.ldd.go.th/web_OLP/Lu_61/Lu61_N/map...
99,2561,เชียงใหม่,510952,589331,661781.0,56416,877150,95039.0,684879.0,13043,22.0,2612.0,700.0,8451499.0,304005.0,120384,23868,175230,12566911,http://www1.ldd.go.th/web_OLP/Lu_61/Lu61_N/map...
100,2561,ตาก,189891,294710,1025116.0,86329,84450,15811.0,669603.0,57486,NaN,279.0,35.0,7192627.0,355744.0,188836,3371,89868,10254156,http://www1.ldd.go.th/web_OLP/Lu_61/Lu61_N/map...
101,2561,นครสวรรค์,399030,2642943,1837079.0,76260,66247,42586.0,NaN,19956,NaN,14931.0,5118.0,577478.0,13111.0,171690,22052,110067,5998548,http://www1.ldd.go.th/web_OLP/Lu_61/Lu61_N/map...
102,2561,น่าน,139022,226033,509963.0,412765,205342,1353.0,1169380.0,919,NaN,193.0,372.0,4316212.0,113182.0,51890,582,22843,7170045,http://www1.ldd.go.th/web_OLP/Lu_61/Lu61_N/map...
103,2561,พะเยา,150485,745124,362811.0,241037,157551,3193.0,92020.0,2059,NaN,11672.0,253.0,2004467.0,57285.0,74283,10844,46328,3959412,http://www1.ldd.go.th/web_OLP/Lu_61/Lu61_N/map...
104,2561,พิจิตร,211780,2087757,193647.0,35438,123191,7007.0,NaN,4835,516.0,4536.0,397.0,18948.0,NaN,88064,4191,51576,2831883,http://www1.ldd.go.th/web_OLP/Lu_61/Lu61_N/map...
105,2561,พิษณุโลก,369885,1699934,1113560.0,517257,187855,4315.0,34.0,8121,235.0,4752.0,481.0,2387204.0,196361.0,128742,17893,123280,6759909,http://www1.ldd.go.th/web_OLP/Lu_61/Lu61_N/map...
106,2561,เพชรบูรณ์,370367,1306637,2361928.0,450517,378082,14152.0,16213.0,28482,NaN,7919.0,2796.0,2049456.0,686271.0,91716,1410,151814,7917760,http://www1.ldd.go.th/web_OLP/Lu_61/Lu61_N/map...
107,2561,แพร่,142700,385531,452599.0,270826,77615,672.0,10643.0,3403,NaN,622.0,639.0,2589038.0,57597.0,45560,3194,45985,4086624,http://www1.ldd.go.th/web_OLP/Lu_61/Lu61_N/map...
108,2561,แม่ฮ่องสอน,84427,138209,120821.0,8722,13100,2608.0,932579.0,243,NaN,NaN,NaN,6472680.0,97536.0,26109,16866,11887,7925787,http://www1.ldd.go.th/web_OLP/Lu_61/Lu61_N/map...
109,2561,ลำปาง,320265,633479,648258.0,372105,95269,3073.0,45707.0,6885,NaN,1261.0,882.0,5369810.0,84461.0,109484,5973,136814,7833726,http://www1.ldd.go.th/web_OLP/Lu_61/Lu61_N/map...
110,2561,ลำพูน,135554,171267,173898.0,30868,493327,8533.0,544.0,5101,NaN,778.0,161.0,1587955.0,82318.0,34310,4219,87343,2816176,http://www1.ldd.go.th/web_OLP/Lu_61/Lu61_N/map...
111,2561,สุโขทัย,215380,1318401,798312.0,136657,195836,69.0,106.0,13544,NaN,3443.0,1935.0,1196075.0,97569.0,108286,3915,33029,4122557,http://www1.ldd.go.th/web_OLP/Lu_61/Lu61_N/map...
112,2561,อุตรดิตถ์,177557,750538,573723.0,113882,228185,7285.0,24.0,3067,592.0,774.0,593.0,2709665.0,60263.0,219953,2104,50915,4899120,http://www1.ldd.go.th/web_OLP/Lu_61/Lu61_N/map...
113,2561,อุทัยธานี,142023,608159,1009668.0,103069,27941,1601.0,NaN,3967,NaN,2098.0,98.0,2164276.0,28383.0,72883,29344,12894,4206404,http://www1.ldd.go.th/web_OLP/Lu_61/Lu61_N/map...

In [12]:
area.groupby("จังหวัด").sum().iloc[:,2:7].sort_values("พื้นที่นา", ascending=False)

C:\Users\User\AppData\Local\Temp\ipykernel_4208\3528820197.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby("จังหวัด").sum().iloc[:,2:7].sort_values("พื้นที่นา", ascending=False)

             พื้นที่นา    พืชไร่   ไม้ยืนต้น   ไม้ผล   พืชสวน
จังหวัด
นครสวรรค์      5324814  3607954.0      163770  133756  84576.0
อุบลราชธานี    4734233   692344.0      948313   56654  11819.0
พิจิตร         4211392   365862.0       70734  236088  11750.0
นครราชสีมา     4044133  4115236.0      373974  193212  30987.0
ร้อยเอ็ด       3607077   377028.0      223369    6579   2780.0
...                ...        ...         ...     ...      ...
พังงา            12459     3924.0     2075599   78287    347.0
สมุทรสาคร        10119       17.0         617  111330  19858.0
ระนอง             6684      577.0     1332558  120326    159.0
สมุทรสงคราม       3710        7.0         403  103007    326.0
ภูเก็ต            3235     3239.0      179957   19435   1112.0

[79 rows x 5 columns]

In [13]:
phone_usage = pd.read_csv("https://catalogapi.nso.go.th/api/index?table=ICTH_43_02&format=csv")
phone_usage

,YEAR,REGION,AREA,SEX,POP_TOTAL,POP_USE_COM,POP_NOT_USE_COM,POP_USE_IN,POP_NOT_USE_IN,POP_USE_MO,POP_NOT_USE_MO,UNIT,SOURCE
0,2557,1) กรุงเทพมหานคร,1) ในเขตเทศบาล,1. ชาย,3870011.0,2130470.0,1739541.0,2119057.0,1750954.0,3473007.0,397004.0,คน,สำนักงานสถิติแห่งชาติ
1,2557,1) กรุงเทพมหานคร,1) ในเขตเทศบาล,2. หญิง,4132114.0,2238258.0,1893856.0,2239788.0,1892326.0,3661258.0,470856.0,คน,สำนักงานสถิติแห่งชาติ
2,2557,2) ภาคกลาง,1) ในเขตเทศบาล,1. ชาย,3935390.0,1848917.0,2086473.0,1704756.0,2230634.0,3392845.0,542545.0,คน,สำนักงานสถิติแห่งชาติ
3,2557,2) ภาคกลาง,1) ในเขตเทศบาล,2. หญิง,4203327.0,1900368.0,2302959.0,1781389.0,2421938.0,3529997.0,673330.0,คน,สำนักงานสถิติแห่งชาติ
4,2557,2) ภาคกลาง,2) นอกเขตเทศบาล,1. ชาย,4734797.0,1574641.0,3160156.0,1574768.0,3160029.0,3784879.0,949918.0,คน,สำนักงานสถิติแห่งชาติ
...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,2563,4) ภาคตะวันออกเฉียงเหนือ,2) นอกเขตเทศบาล,2. หญิง,6236.6,1249.0,4987.6,4279.2,1957.4,5845.5,391.1,พันคน,สำนักงานสถิติแห่งชาติ
140,2563,5) ภาคใต้,1) ในเขตเทศบาล,1. ชาย,1394.1,364.1,1030.0,1169.0,225.1,1333.1,61.0,พันคน,สำนักงานสถิติแห่งชาติ
141,2563,5) ภาคใต้,1) ในเขตเทศบาล,2. หญิง,1514.7,456.2,1058.6,1244.7,270.1,1443.1,71.7,พันคน,สำนักงานสถิติแห่งชาติ
142,2563,5) ภาคใต้,2) นอกเขตเทศบาล,1. ชาย,2847.2,548.3,2298.8,2187.0,660.1,2678.7,168.5,พันคน,สำนักงานสถิติแห่งชาติ
143,2563,5) ภาคใต้,2) นอกเขตเทศบาล,2. หญิง,2906.2,667.6,2238.6,2175.9,730.3,2702.9,203.2,พันคน,สำนักงานสถิติแห่งชาติ